In [15]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [16]:
headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=headers).text

In [17]:
soup = BeautifulSoup(webpage,'lxml')

In [26]:
#soup.find_all('h2')

In [28]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [35]:
for i in soup.find_all('div',style = 'height:auto;'):
    print(i.text.strip())

3.3
3.7
3.6
3.7
3.6
3.8
3.5
3.4
4.0
3.4
3.6
3.9
4.4
3.6
3.6
3.9
3.9
4.6
3.6
3.9

In [38]:
for i in soup.find_all('span',class_='companyCardWrapper__companyRatingCount'):
    print(i.text.strip())

(1.1L)
(73.8k)
(65.4k)
(61.7k)
(53.7k)
(52.7k)
(49k)
(46.2k)
(46.1k)
(43.5k)
(42.6k)
(38.9k)
(33.7k)
(33.4k)
(32.4k)
(31.6k)
(27.5k)
(27.2k)
(26.6k)
(25.9k)

In [39]:
for i in soup.find_all('span',class_='companyCardWrapper__interLinking'):
    print(i.text.strip())

IT Services & Consulting | Bengaluru +444 other locations
IT Services & Consulting | Bengaluru +259 other locations
IT Services & Consulting | Hyderabad +374 other locations
IT Services & Consulting | Hyderabad +232 other locations
IT Services & Consulting | Bengaluru +182 other locations
Banking | Mumbai +1853 other locations
IT Services & Consulting | Bengaluru +246 other locations
IT Services & Consulting | Chennai +231 other locations
Banking | Mumbai +1445 other locations
IT Services & Consulting | Hyderabad +321 other locations
Analytics & KPO | Hyderabad +181 other locations
BPO | Mumbai +256 other locations
Telecom | Mumbai +1959 other locations
Banking | Mumbai +1523 other locations
BPO | Bengaluru +183 other locations
Internet | Bengaluru +516 other locations
Retail | Mumbai +1161 other locations
BPO | Noida +53 other locations
IT Services & Consulting | Bengaluru +145 other locations
IT Services & Consulting | Bengaluru +162 other locations

In [41]:
company = soup.find_all('div',class_='companyCardWrapper')

In [42]:
len(company)

20

In [68]:
name=[]
rating=[]
reviewscount=[]
details=[]

for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div',style = 'height:auto;').text.strip())
    reviewscount.append(i.find('span',class_='companyCardWrapper__companyRatingCount').text.strip())
    details.append(i.find_all('span',class_='companyCardWrapper__interLinking')[0].text.strip())
d={'Name':name,'Rating':rating,'Reviews':reviewscount,'Details':details}
df=pd.DataFrame(d)
df

,Name,Rating,Reviews,Details
0,TCS,3.3,(1.1L),IT Services & Consulting | Bengaluru +444 othe...
1,Accenture,3.7,(73.8k),IT Services & Consulting | Bengaluru +259 othe...
2,Wipro,3.6,(65.4k),IT Services & Consulting | Hyderabad +374 othe...
3,Cognizant,3.7,(61.7k),IT Services & Consulting | Hyderabad +232 othe...
4,Capgemini,3.6,(53.7k),IT Services & Consulting | Bengaluru +182 othe...
5,HDFC Bank,3.8,(52.7k),Banking | Mumbai +1853 other locations
6,Infosys,3.5,(49k),IT Services & Consulting | Bengaluru +246 othe...
7,HCLTech,3.4,(46.2k),IT Services & Consulting | Chennai +231 other ...
8,ICICI Bank,4.0,(46.1k),Banking | Mumbai +1445 other locations
9,Tech Mahindra,3.4,(43.5k),IT Services & Consulting | Hyderabad +321 othe...
10,Genpact,3.6,(42.6k),Analytics & KPO | Hyderabad +181 other locations
11,TP,3.9,(38.9k),BPO | Mumbai +256 other locations
12,Jio,4.4,(33.7k),Telecom | Mumbai +1959 other locations
13,Axis Bank,3.6,(33.4k),Banking | Mumbai +1523 other locations
14,Concentrix Corporation,3.6,(32.4k),BPO | Bengaluru +183 other locations
15,Amazon,3.9,(31.6k),Internet | Bengaluru +516 other locations
16,Reliance Retail,3.9,(27.5k),Retail | Mumbai +1161 other locations
17,iEnergizer,4.6,(27.2k),BPO | Noida +53 other locations
18,LTIMindtree,3.6,(26.6k),IT Services & Consulting | Bengaluru +145 othe...
19,IBM,3.9,(25.9k),IT Services & Consulting | Bengaluru +162 othe...

In [70]:
df.shape

(20, 4)

In [82]:
final = pd.DataFrame()

for j in range(1, 100):

    url = f'https://www.ambitionbox.com/list-of-companies?page={j}'

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
    }

    webpage = requests.get(url, headers=headers).text

    soup = BeautifulSoup(webpage, 'lxml')

    company = soup.find_all('div', class_='companyCardWrapper')

    name = []
    rating = []
    reviewscount = []
    details = []

    for i in company:

        name.append(i.find('h2').text.strip())

        rating.append(
            i.find('div', style='height:auto;').text.strip()
        )

        reviewscount.append(
            i.find(
                'span',
                class_='companyCardWrapper__companyRatingCount'
            ).text.strip()
        )

        details.append(
            i.find_all(
                'span',
                class_='companyCardWrapper__interLinking'
            )[0].text.strip()
        )

    d = {
        'Name': name,
        'Rating': rating,
        'Reviews': reviewscount,
        'Details': details
    }

    df = pd.DataFrame(d)

    final = pd.concat([final, df], ignore_index=True)

In [84]:
final

,Name,Rating,Reviews,Details
0,TCS,3.3,(1.1L),IT Services & Consulting | Bengaluru +444 othe...
1,Accenture,3.7,(73.8k),IT Services & Consulting | Bengaluru +259 othe...
2,Wipro,3.6,(65.4k),IT Services & Consulting | Hyderabad +374 othe...
3,Cognizant,3.7,(61.7k),IT Services & Consulting | Hyderabad +232 othe...
4,Capgemini,3.6,(53.7k),IT Services & Consulting | Bengaluru +182 othe...
...,...,...,...,...
1975,Kellogg Brown and Root,4.1,(556),Engineering & Construction | Chennai +36 other...
1976,Practo,2.9,(555),Internet | Bengaluru +24 other locations
1977,Courtyard by Marriott,4.2,(555),Hospitality | Mumbai +41 other locations
1978,Craftsman Automation,3.8,(556),Auto Components | Coimbatore +26 other locations
1979,Unimoni,3.9,(555),Travel & Tourism | Chennai +137 other locations

In [85]:
df.to_csv('top_recruiting_companies.csv')