In [1]:
import pandas as pd
import numpy as np

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [8]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

<h1>Working with dates</h1>

In [9]:
#converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

**1.Extract Year**

In [12]:
date['date_year']  = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

**2.Extract Month**

In [13]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [14]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

**2.Extract Days**

In [16]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow,date_day
0,2019-12-10,5628,25,3,2019,12,December,10,10
1,2018-08-15,3646,14,157,2018,8,August,15,15
2,2018-10-23,1859,25,1,2018,10,October,23,23
3,2019-08-17,7292,25,1,2019,8,August,17,17
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [17]:
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow,date_day
0,2019-12-10,5628,25,3,2019,12,December,1,10
1,2018-08-15,3646,14,157,2018,8,August,2,15
2,2018-10-23,1859,25,1,2018,10,October,1,23
3,2019-08-17,7292,25,1,2019,8,August,5,17
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [20]:
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_day,date_dow_name
0,2019-12-10,2019,12,December,1,10,Tuesday
1,2018-08-15,2018,8,August,2,15,Wednesday
2,2018-10-23,2018,10,October,1,23,Tuesday
3,2019-08-17,2019,8,August,5,17,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

**is weekend or not**

In [27]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_day,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,1,10,Tuesday,0
1,2018-08-15,2018,8,August,2,15,Wednesday,0
2,2018-10-23,2018,10,October,1,23,Tuesday,0
3,2019-08-17,2019,8,August,5,17,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

**Extract Week of the year**

In [30]:
date['date_week'] = (np.ceil(date['date'].dt.day_of_year / 7)).astype(int)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow,date_day,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,1,10,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,2,15,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,1,23,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,5,17,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [31]:
date['quarter'] = date['date'].dt.quarter
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow,date_day,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,1,10,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,2,15,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,1,23,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,5,17,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

In [32]:
import datetime

today = datetime.datetime.today()

today
# time elapsed
today - date['date']

0     2406 days 16:33:07.354294
1     2888 days 16:33:07.354294
2     2819 days 16:33:07.354294
3     2521 days 16:33:07.354294
4     2744 days 16:33:07.354294
                 ...
995   2834 days 16:33:07.354294
996   2775 days 16:33:07.354294
997   2623 days 16:33:07.354294
998   2688 days 16:33:07.354294
999   2462 days 16:33:07.354294
Name: date, Length: 1000, dtype: timedelta64[ns]

In [33]:
# days passed
(today - date['date']).dt.days

0      2406
1      2888
2      2819
3      2521
4      2744
       ...
995    2834
996    2775
997    2623
998    2688
999    2462
Name: date, Length: 1000, dtype: int64

In [34]:
# month passed
(today - date['date']).dt.days // 12

0      200
1      240
2      234
3      210
4      228
      ...
995    236
996    231
997    218
998    224
999    205
Name: date, Length: 1000, dtype: int64

<h1>Time Data</h1>

In [35]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [36]:
#coverting date time datatype
time['date'] = pd.to_datetime(time['date'])

In [37]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [39]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

**Extract Time Part**

In [40]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

**Time difference**

In [41]:
today-time['date']

0     4592 days 15:43:07.354294
1     4456 days 16:53:07.354294
2     4942 days 16:12:07.354294
3     4244 days 16:02:07.354294
4     4641 days 17:22:07.354294
                 ...
995   5231 days 15:43:07.354294
996   4552 days 17:19:07.354294
997   5017 days 16:56:07.354294
998   5133 days 16:59:07.354294
999   4405 days 17:08:07.354294
Name: date, Length: 1000, dtype: timedelta64[ns]

In [42]:
#in seconds
(today - time['date'])/np.timedelta64(1,'s')

0      3.968054e+08
1      3.850592e+08
2      4.270471e+08
3      3.667393e+08
4      4.010449e+08
           ...
995    4.520150e+08
996    3.933551e+08
997    4.335298e+08
998    4.435523e+08
999    3.806537e+08
Name: date, Length: 1000, dtype: float64

In [43]:
#in minutes
(today - time['date'])/np.timedelta64(1,'m')

0      6.613423e+06
1      6.417653e+06
2      7.117452e+06
3      6.112322e+06
4      6.684082e+06
           ...
995    7.533583e+06
996    6.555919e+06
997    7.225496e+06
998    7.392539e+06
999    6.344228e+06
Name: date, Length: 1000, dtype: float64

In [44]:
#in hours
(today - time['date'])/np.timedelta64(1,'h')

0      110223.718710
1      106960.885376
2      118624.202043
3      101872.035376
4      111401.368710
           ...
995    125559.718710
996    109265.318710
997    120424.935376
998    123208.985376
999    105737.135376
Name: date, Length: 1000, dtype: float64